name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "ndb01"
database_name = "ndb01"
database_id = "bf2d78f7-8265-4748-958c-ee539be62163"
